version: '3.0'
services:
  # rabbitmq:
  #   hostname: rabbitmq
  #   container_name: rabbitmq_rb
  #   image: rabbitmq:3.7-management
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "admin"
  #     RABBITMQ_DEFAULT_PASS: "12345678"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "14250"
        - "9411:9411"
        - "16686:16686"
        - "16687"
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        - LOG_LEVEL=debug
    restart: on-failure

  temcriptografia:  
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      # - rabbitmq
      - jaeger
    links:
      # - rabbitmq
      - jaeger
      # environment:
      #   APP_CONFIG_FILE: '../config/production.py'  
    # command: "ls"